<a href="https://colab.research.google.com/github/2303a52074/Generative-AI-2025/blob/main/2303A52074_1_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1

In [12]:
import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

Y_actual = np.array([20, 30, 40, 50, 60])
Y_pred = np.array([20.5, 30.3, 40.2, 50.6, 60.7])

def mean_absolute_error_scratch(y_true, y_pred):
    return np.mean(np.abs(y_true - y_pred))

def mean_squared_error_scratch(y_true, y_pred):
    return np.mean((y_true - y_pred) ** 2)

def root_mean_squared_error_scratch(y_true, y_pred):
    return np.sqrt(mean_squared_error_scratch(y_true, y_pred))

def r2_score_scratch(y_true, y_pred):
    ss_total = np.sum((y_true - np.mean(y_true)) ** 2)
    ss_residual = np.sum((y_true - y_pred) ** 2)
    return 1 - (ss_residual / ss_total)

mae_scratch = mean_absolute_error_scratch(Y_actual, Y_pred)
mse_scratch = mean_squared_error_scratch(Y_actual, Y_pred)
rmse_scratch = root_mean_squared_error_scratch(Y_actual, Y_pred)
r2_scratch = r2_score_scratch(Y_actual, Y_pred)

mae_sklearn = mean_absolute_error(Y_actual, Y_pred)
mse_sklearn = mean_squared_error(Y_actual, Y_pred)
rmse_sklearn = np.sqrt(mse_sklearn)
r2_sklearn = r2_score(Y_actual, Y_pred)

print(f"Custom (Scratch) Error Metrics:")
print(f"Mean Absolute Error (MAE): {mae_scratch}")
print(f"Mean Squared Error (MSE): {mse_scratch}")
print(f"Root Mean Squared Error (RMSE): {rmse_scratch}")
print(f"R-squared (R²): {r2_scratch}")

print("\nSklearn Error Metrics:")
print(f"Mean Absolute Error (MAE): {mae_sklearn}")
print(f"Mean Squared Error (MSE): {mse_sklearn}")
print(f"Root Mean Squared Error (RMSE): {rmse_sklearn}")
print(f"R-squared (R²): {r2_sklearn}")


Custom (Scratch) Error Metrics:
Mean Absolute Error (MAE): 0.4600000000000016
Mean Squared Error (MSE): 0.24600000000000147
Root Mean Squared Error (RMSE): 0.49598387070549127
R-squared (R²): 0.99877

Sklearn Error Metrics:
Mean Absolute Error (MAE): 0.4600000000000016
Mean Squared Error (MSE): 0.24600000000000147
Root Mean Squared Error (RMSE): 0.49598387070549127
R-squared (R²): 0.99877


2

In [13]:
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix as cm_sklearn
def calculate_metrics(y_actual, y_pred, num_classes):
    cm = np.zeros((num_classes, num_classes), dtype=int)
    for true, pred in zip(y_actual, y_pred):
        cm[true, pred] += 1
    acc = accuracy_score(y_actual, y_pred)
    print(f"Accuracy: {acc}")
    for class_label in range(num_classes):
        tp, fp, fn = cm[class_label, class_label], cm[:, class_label].sum() - cm[class_label, class_label], cm[class_label, :].sum() - cm[class_label, class_label]
        precision = tp / (tp + fp) if tp + fp > 0 else 0
        recall = tp / (tp + fn) if tp + fn > 0 else 0
        f1 = 2 * (precision * recall) / (precision + recall) if precision + recall > 0 else 0
        print(f"Class {class_label}: Precision: {precision}, Recall: {recall}, F1 Score: {f1}")
    print("\nConfusion Matrix:")
    print(cm)
y_actual = [0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2]
y_pred = [0, 0, 1, 2, 2, 1, 0, 2, 0, 2, 0, 0, 1, 2, 2]
num_classes = 3
calculate_metrics(y_actual, y_pred, num_classes)
print("\nUsing scikit-learn:")
print(f"Accuracy: {accuracy_score(y_actual, y_pred)}")
print(f"Precision (per class): {precision_score(y_actual, y_pred, average=None, labels=[0, 1, 2])}")
print(f"Recall (per class): {recall_score(y_actual, y_pred, average=None, labels=[0, 1, 2])}")
print(f"F1 Score (per class): {f1_score(y_actual, y_pred, average=None, labels=[0, 1, 2])}")
print(f"Confusion Matrix:\n{cm_sklearn(y_actual, y_pred)}")

Accuracy: 0.3333333333333333
Class 0: Precision: 0.3333333333333333, Recall: 0.4, F1 Score: 0.3636363636363636
Class 1: Precision: 0.3333333333333333, Recall: 0.2, F1 Score: 0.25
Class 2: Precision: 0.3333333333333333, Recall: 0.4, F1 Score: 0.3636363636363636

Confusion Matrix:
[[2 1 2]
 [2 1 2]
 [2 1 2]]

Using scikit-learn:
Accuracy: 0.3333333333333333
Precision (per class): [0.33333333 0.33333333 0.33333333]
Recall (per class): [0.4 0.2 0.4]
F1 Score (per class): [0.36363636 0.25       0.36363636]
Confusion Matrix:
[[2 1 2]
 [2 1 2]
 [2 1 2]]
